"""Build js/site-footer.js: the site footer, for the project sites.

The project sites (PELE, Mother Lode, secchi, ...) are separate repos with
their own designs. Each one loads this with a single line:

    <script src="https://brooksgroves.com/js/site-footer.js" defer></script>

and gets the same footer as the main site at the bottom of the page.

Sources, so the footer is still edited in one place:
  * the markup is the <footer> in tags.html (every page here carries the
    same one), with links made absolute and "More here" pointed at the
    main sections;
  * the styles are css/site-footer.css.

The footer is drawn inside a shadow root, so a project's own CSS can't
restyle it and its styles can't leak into the project. The deploy workflow
runs this before every build, so a change to the footer reaches every
project on the next deploy.

    python scripts/build_footer_js.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://brooksgroves.com"

# Colours the footer CSS reads from the main site's :root.
VARS = {"--ink": "#1c1a16", "--stone": "#7a7268", "--white": "#fdfaf4",
        "--gold": "#c8922a", "--mist": "#d6d0c4", "--parchment": "#f5f0e8"}

MORE_HERE = ('<a href="/#work">Projects</a>\n        <a href="/blog/">Blog</a>\n'
             '        <a href="/maps.html">Maps</a>\n        <a href="/writing/">Writing</a>')


def footer_markup() -> str:
    s = (ROOT / "tags.html").read_text(encoding="utf-8")
    m = re.search(r"<footer>.*?</footer>", s, flags=re.S)
    if not m:
        raise SystemExit("no <footer> in tags.html")
    html = m.group(0)
    html = re.sub(r'(<div class="pagelink-row">).*?(</div>)',
                  lambda x: f"{x.group(1)}\n        {MORE_HERE}\n      {x.group(2)}", html, count=1, flags=re.S)
    html = html.replace('href="#top"', 'href="#"')
    html = re.sub(r'href="/', f'href="{SITE}/', html)
    return html


def footer_css() -> str:
    css = (ROOT / "css" / "site-footer.css").read_text(encoding="utf-8")
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    css = css.replace("html footer", "footer")
    host = ":host{all:initial;display:block;" + "".join(f"{k}:{v};" for k, v in VARS.items()) + "}\n"
    # The main site's page CSS sets these on the footer's surroundings; a
    # project page has none of it, so the footer brings its own.
    base = ("footer{display:block;font-family:'Libre Baskerville',Georgia,serif;line-height:1.6;"
            "margin-top:0;text-align:left}\n"
            "footer *{box-sizing:border-box}\n footer p{margin:0}\n")
    return host + base + re.sub(r"\s+", " ", css).strip()


JS = """/* site-footer.js: the brooksgroves.com footer for the project sites.
   GENERATED by scripts/build_footer_js.py from tags.html and
   css/site-footer.css. Edit those, not this. */
(function () {
  if (document.querySelector('bg-site-footer')) return;
  var CSS = %s;
  var HTML = %s;
  var FONTS = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Libre+Baskerville&family=DM+Mono:wght@400&display=swap';
  function mount() {
    if (!document.querySelector('link[href*="Playfair+Display"]')) {
      var l = document.createElement('link');
      l.rel = 'stylesheet'; l.href = FONTS; document.head.appendChild(l);
    }
    var host = document.createElement('bg-site-footer');
    var root = host.attachShadow({ mode: 'open' });
    root.innerHTML = '<style>' + CSS + '</style>' + HTML;
    var top = root.querySelector('a[href="#"]');
    if (top) top.addEventListener('click', function (e) { e.preventDefault(); window.scrollTo({ top: 0, behavior: 'smooth' }); });
    document.body.appendChild(host);
  }
  if (document.body) mount(); else document.addEventListener('DOMContentLoaded', mount);
})();
"""


def main() -> None:
    out = ROOT / "js" / "site-footer.js"
    out.parent.mkdir(exist_ok=True)
    out.write_text(JS % (json.dumps(footer_css()), json.dumps(footer_markup())), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
