"""
Homepage topic cards, built from the post list in tags.html.

    python3 scripts/home_topics.py

Reads POSTS from tags.html and the topic definitions in data/topics.json.
Each post belongs to the first topic that shares one of its tags. Writes:
  * index.html, between <!-- TOPICS:START --> and <!-- TOPICS:END -->:
    the newest post, then one card per topic (count, newest two titles,
    a link to see them all)
  * tags.html, between /* TOPICS:START */ and /* TOPICS:END */: the topic
    definitions, so tags.html#topic=<id> lists exactly what the card counted

The Home topics workflow runs this whenever tags.html or data/topics.json
changes, so adding a post to tags.html is all it takes.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def posts():
    s = (ROOT / "tags.html").read_text(encoding="utf-8")
    a = s.index("const POSTS = [")
    b = s.index("];", a)
    return json.loads(s[a + len("const POSTS = "):b + 1])


def topic_of(post, topics, fallback):
    tags = set(post["tags"])
    for t in topics:
        if tags & set(t["tags"]):
            return t["id"]
    return fallback


def strip_icon(title: str) -> str:
    """Titles start with an emoji; the card already has one."""
    return re.sub(r"^[^\w\"'“‘(]+", "", title).strip()


def local(url: str) -> str:
    return url.replace("https://brooksgroves.com", "") or "/"


def esc(s):
    return html.escape(s, quote=True)


def build():
    cfg = json.loads((ROOT / "data/topics.json").read_text(encoding="utf-8"))
    topics, fallback = cfg["topics"], cfg.get("fallback", cfg["topics"][-1]["id"])
    hidden = tuple("https://" + h for h in cfg.get("exclude_hosts", []))
    skip = set(cfg.get("exclude_urls", []))
    ps = [p for p in posts() if not p["url"].startswith(hidden) and p["url"] not in skip]   # gated sites stay off
    groups = {t["id"]: [] for t in topics}
    for p in ps:                                     # POSTS is newest first
        groups[topic_of(p, topics, fallback)].append(p)

    newest = ps[0]
    out = ['<!-- TOPICS:START (generated by scripts/home_topics.py; edit data/topics.json) -->',
           f'      <a href="{esc(local(newest["url"]))}" class="writing-item latest-item">',
           '        <div class="writing-type">Latest</div>',
           f'        <div class="writing-hed">{esc(newest["title"])}</div>',
           f'        <div class="writing-dek">{esc(newest["dek"])}</div>',
           '      </a>',
           '      <div class="topic-grid">']
    order = sorted(topics, key=lambda t: -len(groups[t["id"]]))
    for t in order:
        g = groups[t["id"]]
        if not g:
            continue
        items = "".join(
            f'<li><a href="{esc(local(p["url"]))}">{esc(strip_icon(p["title"]))}</a></li>' for p in g[:2])
        n = len(g)
        out += [
            f'        <section class="topic-card" aria-labelledby="topic-{t["id"]}">',
            f'          <h3 class="topic-name" id="topic-{t["id"]}"><span class="topic-icon" aria-hidden="true">{t["icon"]}</span>{esc(t["name"])}</h3>',
            f'          <p class="topic-blurb">{esc(t["blurb"])}</p>',
            f'          <ul class="topic-latest">{items}</ul>',
            f'          <a class="topic-all" href="/tags.html#topic={t["id"]}">All {n} {"entry" if n == 1 else "entries"} &rarr;</a>',
            '        </section>']
    out += ['      </div>', '      <!-- TOPICS:END -->']
    block = "\n".join(out)

    idx = ROOT / "index.html"
    s = idx.read_text(encoding="utf-8")
    s2 = re.sub(r"<!-- TOPICS:START.*?<!-- TOPICS:END -->", lambda m: block, s, flags=re.S)
    if s2 == s and "TOPICS:START" not in s:
        raise SystemExit("index.html has no TOPICS markers")
    idx.write_text(s2, encoding="utf-8")

    tg = ROOT / "tags.html"
    s = tg.read_text(encoding="utf-8")
    js = ("/* TOPICS:START (generated by scripts/home_topics.py) */\nconst TOPICS = "
          + json.dumps([{k: t[k] for k in ("id", "name", "tags")} for t in topics], ensure_ascii=False)
          + f";\nconst TOPIC_FALLBACK = {json.dumps(fallback)};\n"
          + f"const TOPIC_HIDDEN = {json.dumps(list(hidden))};\n"
          + f"const TOPIC_SKIP = {json.dumps(sorted(skip))};\n/* TOPICS:END */")
    s2 = re.sub(r"/\* TOPICS:START.*?/\* TOPICS:END \*/", lambda m: js, s, flags=re.S)
    tg.write_text(s2, encoding="utf-8")
    print(", ".join(f"{t['name']} {len(groups[t['id']])}" for t in order), f"| {len(ps)} posts")


if __name__ == "__main__":
    build()
